[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.115.8",
    "jigsawstack>=0.1.29",
    "langchain[openai]>=0.3.20",
    "langchain-openai>=0.3.7",
    "pandas>=2.2.3",
    "pydantic-settings>=2.8.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
    "langchain-community>=0.3.19",
    "langgraph>=0.3.5",
    "langchain-anthropic>=0.3.9",
    "tavily-python>=0.5.1",
    "langgraph-checkpoint-sqlite>=2.0.5",
    "bs4>=0.0.2",
<<<<<<< HEAD
    "python-telegram-bot>=21.11.1",
=======
    "crawl4ai>=0.5.0.post4",
    "chardet>=5.2.0",
>>>>>>> 5c9ef3b8a1792f71d6c01d558e80defc99c8650f
    "playwright>=1.50.0",
]
